// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tIGwDE0de07EN1jX2KzAOJG9gmueljg',
    appId: '1:1081722589385:web:025f3b40d5f4dcc1387d18',
    messagingSenderId: '1081722589385',
    projectId: 'trustdine-fae14',
    authDomain: 'trustdine-fae14.firebaseapp.com',
    storageBucket: 'trustdine-fae14.appspot.com',
    measurementId: 'G-SQPF7NKDR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ahfF8NS4odQzb3jYy9JVNiJ00nkQ55A',
    appId: '1:1081722589385:android:7796f574e0f9a4db387d18',
    messagingSenderId: '1081722589385',
    projectId: 'trustdine-fae14',
    storageBucket: 'trustdine-fae14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXL31mdDVmClhWgqsuwSuiOfB1qW_i5RM',
    appId: '1:1081722589385:ios:fd2000f7d42483c2387d18',
    messagingSenderId: '1081722589385',
    projectId: 'trustdine-fae14',
    storageBucket: 'trustdine-fae14.appspot.com',
    iosBundleId: 'com.example.trustdineReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXL31mdDVmClhWgqsuwSuiOfB1qW_i5RM',
    appId: '1:1081722589385:ios:8d83e7511c2d8f35387d18',
    messagingSenderId: '1081722589385',
    projectId: 'trustdine-fae14',
    storageBucket: 'trustdine-fae14.appspot.com',
    iosBundleId: 'com.example.trustdineReader.RunnerTests',
  );
}
